addSbtPlugin("com.eed3si9n"  % "sbt-assembly" % "1.1.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.5")
addSbtPlugin("com.dwijnand"  % "sbt-dynver"   % "4.1.1")
//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.20")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo" % "0.10.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"  % "0.9.31")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "1.9.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.2")
